/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.vistas;

import app.modelo.Carta;
import app.modelo.ElementoCarta;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enrique
 */
public class VistaCarta extends javax.swing.JFrame {

    private final VistaPrincipal padre; 
    private final Carta carta;
    
    public VistaCarta(VistaPrincipal padre) {
        initComponents();
        this.padre = padre;
        carta = new Carta();
        anadirModelos();
    }
    
    private void anadirModelos(){
        DefaultTableModel dtmEnsaladas = new DefaultTableModel();
        dtmEnsaladas.setColumnIdentifiers(new String[]{"Nombre","Precio","Descripcion"});
        
        List<ElementoCarta> lista = carta.getEnsaladas();
        for (var item : lista){
            dtmEnsaladas.addRow(item.toArrayString());
        }
        
        jTableEnsaladas.setModel(dtmEnsaladas);        
        
        DefaultTableModel dtmCarnes = new DefaultTableModel();
        dtmCarnes.setColumnIdentifiers(new String[]{"Nombre","Precio","Descripcion"});
        
        lista = carta.getCarnes();
        for (var item : lista){
            dtmCarnes.addRow(item.toArrayString());
        }
        jTableCarnes.setModel(dtmCarnes);
        
        DefaultTableModel dtmPescados = new DefaultTableModel();
        dtmPescados.setColumnIdentifiers(new String[]{"Nombre","Precio","Descripcion"});
        
        lista = carta.getPescados();
        for (var item : lista){
            dtmPescados.addRow(item.toArrayString());
        }
        jTablePescados.setModel(dtmPescados);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTableEnsaladas.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        jTableCarnes.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        jTablePescados.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelEnsaldas = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableEnsaladas = new javax.swing.JTable();
        jPanelCarnes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCarnes = new javax.swing.JTable();
        jPanelPescados = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablePescados = new javax.swing.JTable();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setToolTipText("Secciones de la carta");
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(700, 450));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(700, 450));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(700, 400));

        jTableEnsaladas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTableEnsaladas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableEnsaladas.setPreferredSize(new java.awt.Dimension(640, 331));
        jScrollPane5.setViewportView(jTableEnsaladas);

        javax.swing.GroupLayout jPanelEnsaldasLayout = new javax.swing.GroupLayout(jPanelEnsaldas);
        jPanelEnsaldas.setLayout(jPanelEnsaldasLayout);
        jPanelEnsaldasLayout.setHorizontalGroup(
            jPanelEnsaldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
            .addGroup(jPanelEnsaldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnsaldasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5)))
        );
        jPanelEnsaldasLayout.setVerticalGroup(
            jPanelEnsaldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
            .addGroup(jPanelEnsaldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnsaldasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("ENSALADAS", jPanelEnsaldas);

        jTableCarnes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTableCarnes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableCarnes.setPreferredSize(new java.awt.Dimension(640, 331));
        jScrollPane3.setViewportView(jTableCarnes);

        javax.swing.GroupLayout jPanelCarnesLayout = new javax.swing.GroupLayout(jPanelCarnes);
        jPanelCarnes.setLayout(jPanelCarnesLayout);
        jPanelCarnesLayout.setHorizontalGroup(
            jPanelCarnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
            .addGroup(jPanelCarnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCarnesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3)))
        );
        jPanelCarnesLayout.setVerticalGroup(
            jPanelCarnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
            .addGroup(jPanelCarnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCarnesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("CARNES", jPanelCarnes);

        jTablePescados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTablePescados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTablePescados.setPreferredSize(new java.awt.Dimension(640, 331));
        jScrollPane6.setViewportView(jTablePescados);

        javax.swing.GroupLayout jPanelPescadosLayout = new javax.swing.GroupLayout(jPanelPescados);
        jPanelPescados.setLayout(jPanelPescadosLayout);
        jPanelPescadosLayout.setHorizontalGroup(
            jPanelPescadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
            .addGroup(jPanelPescadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPescadosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6)))
        );
        jPanelPescadosLayout.setVerticalGroup(
            jPanelPescadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
            .addGroup(jPanelPescadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPescadosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("PESCADO", jPanelPescados);

        jButtonVolver.setText("Volver");
        jButtonVolver.setToolTipText("Volver al menú principal");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jButtonVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JPanel jPanelCarnes;
    private javax.swing.JPanel jPanelEnsaldas;
    private javax.swing.JPanel jPanelPescados;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCarnes;
    private javax.swing.JTable jTableEnsaladas;
    private javax.swing.JTable jTablePescados;
    // End of variables declaration//GEN-END:variables
}
