/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.vistas;

import app.modelo.Carta;
import app.modelo.ElementoCarta;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enrique
 */
public class VistaCarta extends javax.swing.JFrame {

    private final VistaPrincipal padre; 
    private final Carta carta;
    
    public VistaCarta(VistaPrincipal padre) {
        initComponents();
        this.padre = padre;
        carta = new Carta();
        anadirModelos();
        
        
    }
    
    private void anadirModelos(){
        DefaultTableModel dtmEnsaladas = new DefaultTableModel();
        dtmEnsaladas.setColumnIdentifiers(new String[]{"Nombre","Precio","Descripcion"});
        
        List<ElementoCarta> lista = carta.getEnsaladas();
        for (var item : lista){
            dtmEnsaladas.addRow(item.toArrayString());
        }
        jTableEnsaladas.setModel(dtmEnsaladas);
        
        DefaultTableModel dtmCarnes = new DefaultTableModel();
        dtmCarnes.setColumnIdentifiers(new String[]{"Nombre","Precio","Descripcion"});
        
        lista = carta.getCarnes();
        for (var item : lista){
            dtmCarnes.addRow(item.toArrayString());
        }
        jTableCarnes.setModel(dtmCarnes);
        
        DefaultTableModel dtmPescados = new DefaultTableModel();
        dtmPescados.setColumnIdentifiers(new String[]{"Nombre","Precio","Descripcion"});
        
        lista = carta.getPescados();
        for (var item : lista){
            dtmPescados.addRow(item.toArrayString());
        }
        jTablePescados.setModel(dtmPescados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabeceraCarta1 = new app.vistas.paneles.CabeceraCarta();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelEnsaldas = new javax.swing.JPanel();
        jTableEnsaladas = new javax.swing.JTable();
        jPanelEnsaldas1 = new javax.swing.JPanel();
        jTableCarnes = new javax.swing.JTable();
        jPanelEnsaldas2 = new javax.swing.JPanel();
        jTablePescados = new javax.swing.JTable();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableEnsaladas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));

        javax.swing.GroupLayout jPanelEnsaldasLayout = new javax.swing.GroupLayout(jPanelEnsaldas);
        jPanelEnsaldas.setLayout(jPanelEnsaldasLayout);
        jPanelEnsaldasLayout.setHorizontalGroup(
            jPanelEnsaldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(jPanelEnsaldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnsaldasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTableEnsaladas, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelEnsaldasLayout.setVerticalGroup(
            jPanelEnsaldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
            .addGroup(jPanelEnsaldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnsaldasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTableEnsaladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("ENSALADAS", jPanelEnsaldas);

        jTableCarnes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));

        javax.swing.GroupLayout jPanelEnsaldas1Layout = new javax.swing.GroupLayout(jPanelEnsaldas1);
        jPanelEnsaldas1.setLayout(jPanelEnsaldas1Layout);
        jPanelEnsaldas1Layout.setHorizontalGroup(
            jPanelEnsaldas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(jPanelEnsaldas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnsaldas1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTableCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelEnsaldas1Layout.setVerticalGroup(
            jPanelEnsaldas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
            .addGroup(jPanelEnsaldas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnsaldas1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTableCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("CARNES", jPanelEnsaldas1);

        jTablePescados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));

        javax.swing.GroupLayout jPanelEnsaldas2Layout = new javax.swing.GroupLayout(jPanelEnsaldas2);
        jPanelEnsaldas2.setLayout(jPanelEnsaldas2Layout);
        jPanelEnsaldas2Layout.setHorizontalGroup(
            jPanelEnsaldas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(jPanelEnsaldas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnsaldas2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTablePescados, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelEnsaldas2Layout.setVerticalGroup(
            jPanelEnsaldas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
            .addGroup(jPanelEnsaldas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnsaldas2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTablePescados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("PESCADO", jPanelEnsaldas2);

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(cabeceraCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(203, Short.MAX_VALUE)
                    .addComponent(jButtonVolver)
                    .addContainerGap(204, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cabeceraCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(341, Short.MAX_VALUE)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.vistas.paneles.CabeceraCarta cabeceraCarta1;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JPanel jPanelEnsaldas;
    private javax.swing.JPanel jPanelEnsaldas1;
    private javax.swing.JPanel jPanelEnsaldas2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCarnes;
    private javax.swing.JTable jTableEnsaladas;
    private javax.swing.JTable jTablePescados;
    // End of variables declaration//GEN-END:variables
}
