/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.vistas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Enrique
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private VistaPrincipalReservas principal;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        principal = new VistaPrincipalReservas(this);
        principal.setTitle("Gestión Restaurante de Kike");
        principal.setLocationRelativeTo(null);
        this.setIconImage(getIconoRestaurante());
        principal.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }
    
    private Image getIconoRestaurante() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("recursos/tenedor.png"));
       return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBReservas = new javax.swing.JButton();
        jBCarta = new javax.swing.JButton();
        jBEmpleados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBPedidos = new javax.swing.JButton();
        jBAcercaDe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jBReservas.setText("RESERVAS");
        jBReservas.setToolTipText("Gestion de Reservas");
        jBReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBReservasMouseClicked(evt);
            }
        });

        jBCarta.setText("CARTA");
        jBCarta.setToolTipText("Mostrar Carta");
        jBCarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCartaMouseClicked(evt);
            }
        });

        jBEmpleados.setText("EMPLEADOS");
        jBEmpleados.setToolTipText("Gestion de empleados");
        jBEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBEmpleadosMouseClicked(evt);
            }
        });
        jBEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpleadosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OPCIONES DEL PROGRAMA:");

        jBPedidos.setText("PEDIDOS");
        jBPedidos.setToolTipText("Gestion de pedidos");
        jBPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPedidosMouseClicked(evt);
            }
        });
        jBPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPedidosActionPerformed(evt);
            }
        });

        jBAcercaDe.setText("ACERCA DE");
        jBAcercaDe.setToolTipText("Informacion de la aplicacion");
        jBAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAcercaDeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBEmpleados)
                    .addComponent(jBReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCarta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jBAcercaDe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBReservas)
                    .addComponent(jBCarta))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEmpleados)
                    .addComponent(jBPedidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jBAcercaDe)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEmpleadosActionPerformed

    private void jBPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPedidosActionPerformed

    private void jBReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBReservasMouseClicked
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBReservasMouseClicked

    private void jBCartaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCartaMouseClicked
        VistaCarta carta = new VistaCarta(this);
        carta.setTitle("Carta del Restaurante de Kike");
        carta.setLocationRelativeTo(null);
        carta.setVisible(true);
        carta.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_jBCartaMouseClicked

    private void jBEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEmpleadosMouseClicked
        JOptionPane.showMessageDialog(this, "Opción no disponible en esta versión del programa");
    }//GEN-LAST:event_jBEmpleadosMouseClicked

    private void jBPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPedidosMouseClicked
        JOptionPane.showMessageDialog(this, "Opción no disponible en esta versión del programa");
    }//GEN-LAST:event_jBPedidosMouseClicked

    private void jBAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAcercaDeMouseClicked
        JOptionPane.showMessageDialog(this, "Aplicación creada por Enrique Octavio Fernández Chacón para la Tarea Online 1 de Diseño de Interfaces");
    }//GEN-LAST:event_jBAcercaDeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAcercaDe;
    private javax.swing.JButton jBCarta;
    private javax.swing.JButton jBEmpleados;
    private javax.swing.JButton jBPedidos;
    private javax.swing.JButton jBReservas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
